version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 8505:8505
    depends_on:
      - backend
    volumes:
        - ./storage:/storage
  backend:
    build: backend
    ports:
      - 8080:8080
    volumes:
      - ./storage:/storage
